### ISSUE TITLE
Mouse icon duplicate every time paired

### ISSUE THREAD

**Issue by andirsun** [elementary/wingpanel-indicator-bluetooth#115]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
I have a BT mouse and every time i need to pair it again with my laptop the icon duplicates and i cant connect it throw the panel. To connect again need to open bluetooth settings, delete the current mouse icon and re pair again

![Screenshot from 2020-05-08 21-29-15](https://user-images.githubusercontent.com/22928302/81461771-b3153700-9173-11ea-96fa-dde0cd418eb5.png)

### To Reproduce
1. Pair the mouse
2. Pair the mouse with other device
3. try to pair again with elementary
4. Icon doesnt work and need to quit an pair again

### Expected behavior

The correct behavior is see only one icon and when i push the mouse icon then connect normally

## Platform Information

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by danrabbit** [comment]
Should be fixed by #116

**Comment by astaszek** [comment]
I'm experiencing kinda the same problem after having my mouse paired to another laptop.

To reproduce :
1. Pair a BT mouse to eOS
2. Pair the mouse to another OS
3. Pair the mouse back to eOS

Expected behaviour : 
No unpaired devices in the wingpanel window, delete all previous entries related to the re-paired BT device.

Actual behaviour : 
Few old entries in the wingpanel window, few old entries in unpaired devices (which can't be even connected to, so I have to look which one is the good one).


![image](https://user-images.githubusercontent.com/74073424/111609923-1384f400-87db-11eb-82d1-7953b1fd84a8.png)

![image](https://user-images.githubusercontent.com/74073424/111608988-1d5a2780-87da-11eb-8460-dd3fa44f05b9.png)
