### ISSUE TITLE
Update indicator icon

### ISSUE THREAD

**Issue by lenemter** [elementary/wingpanel-indicator-bluetooth#183]
### Problem

The icon uses old color and an old slashie

### Proposal

Update an icon as well as an animation

### Prior Art (Optional)

![image](https://user-images.githubusercontent.com/80143868/208229566-a52f37c5-f8b4-4223-82fc-b4d261c0dfcd.png)

**Comment by stan-janssen** [comment]
I tried to look into this yesterday. If I understand what you mean correctly: the slash should be white instead of grey, like we use on the Wifi, Audio and Notifications indicator icons.

Sure enough, the [symbolic bluetooth status](https://github.com/elementary/icons/blob/master/status/symbolic/bluetooth-disabled-symbolic.svg) icon file stil has the grey slash.

However, in the [elementary/icons](https://github.com/elementary/icons) repository, the [audio-muted](https://github.com/elementary/icons/blob/master/status/symbolic/audio-volume-muted-symbolic.svg) file also still has the grey slash, while the one in my menu bar has the white slash. 

I’m not sure if I’m looking in the right place, so: where should I be looking if these icons if I want to fix this one?

Thanks!

**Comment by lenemter** [comment]
> However, in the [elementary/icons](https://github.com/elementary/icons) repository, the [audio-muted](https://github.com/elementary/icons/blob/master/status/symbolic/audio-volume-muted-symbolic.svg) file also still has the grey slash, while the one in my menu bar has the white slash.

I think the colors on wingpanel are inverted to ensure contrast, that's why you see it as white. If you use light wallpapers the slash turns grey.
![image](https://user-images.githubusercontent.com/80143868/229348900-9b795330-2f5e-4233-ac55-d300f16e8f5f.png)

**Comment by lenemter** [comment]
Seems like Bluetooth icon animation is located in /status/24

**Comment by jeremypw** [comment]
![Screenshot from 2023-04-02 12 19 05](https://user-images.githubusercontent.com/10513844/229349593-0c37c000-3797-41ff-98f8-afad76f4aecb.png)


The slash in `audio-volume-muted-symbolic.symbolic` is actually both white and black rather than grey so its appearance will depend on the background.

**Comment by jeremypw** [comment]
![Screenshot from 2023-04-02 15 14 34](https://user-images.githubusercontent.com/10513844/229358511-38d7933c-26e2-4b14-b5c3-a14ea719f3ee.png)

Compare the equivalent bluetooth icon.  The slash is grey and white.
