### ISSUE TITLE
Bluetooth indicator doesn't show battery percentage

### ISSUE THREAD

**Issue by BenMorant** [elementary/wingpanel-indicator-bluetooth#197]
### Problem

Hello everyone,

The bluetooth indicator doesn't show battery left for the connected devices.

### Proposal

The bluetooth indicator should show battery left for connected devices

**Comment by lenemter** [comment]
Hello. Thanks for reporting! Power indicator already shows battery percentage when available for devices (except bluetooth headphones, see https://github.com/elementary/wingpanel-indicator-power/issues/141). I'll close this issue since this is already implemented and there is a more specific issue for bluetooth headphones.
